//This is a .dbml file to visualize the database. It uses the dbdiagram.io official vscode extension for highlight, suggestion and the visualisation using the open preview icon on the line with the split editor icon

Enum statuses {
    user
    admin

}

Table Users {
    id int [primary key, increment]
    name varchar(15) [not null]
    email varchar(20) [unique, not null]
    email_verified_at date
    password varchar(255) [not null]
    status statuses [default: statuses.user]
    created_at date
    updated_at date
}

Table Tasks {
    id int [primary key, increment]

}
